// KARMA Products Data
const PRODUCTS = [
    {
        id: 1,
        name: "Trust Karma Crewneck",
        category: "crewnecks",
        type: "Crewneck",
        price: 145,
        colors: ["Sand", "Black", "Sage"],
        description: "Oversized heavyweight crewneck with 'TRUST KARMA' chest print. Premium 450gsm French terry cotton.",
        details: ["100% Cotton", "Oversized fit", "Ribbed cuffs & hem", "Screen printed"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        image: "images/hero-trust-karma.jpg",
        featured: true,
        new: true,
        limited: false
    },
    {
        id: 2,
        name: "Believe In Karma Hoodie",
        category: "hoodies",
        type: "Hoodie",
        price: 185,
        colors: ["Cream", "Black", "Charcoal"],
        description: "Premium heavyweight hoodie featuring 'BELIEVE IN KARMA' front print. Double-layered hood with metal aglets.",
        details: ["100% Cotton", "Oversized fit", "Kangaroo pocket", "YKK hardware"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        image: "images/hero-trust-karma.jpg",
        featured: true,
        new: true,
        limited: false
    },
    {
        id: 3,
        name: "KARMA Classic Tee",
        category: "tees",
        type: "T-Shirt",
        price: 75,
        colors: ["Black", "White", "Sand"],
        description: "Essential heavyweight tee with minimal KARMA logo. 280gsm premium cotton.",
        details: ["100% Cotton", "Relaxed fit", "Ribbed collar", "Back neck print"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        image: "images/hero-trust-karma.jpg",
        featured: false,
        new: false,
        limited: false
    },
    {
        id: 4,
        name: "What Goes Around Hoodie",
        category: "hoodies",
        type: "Hoodie",
        price: 195,
        colors: ["Black", "Washed Black"],
        description: "Limited edition hoodie with full back print 'What Goes Around Comes Around'. Vintage wash finish.",
        details: ["100% Cotton", "Oversized fit", "Vintage wash", "Limited run"],
        sizes: ["S", "M", "L", "XL"],
        image: "images/hero-trust-karma.jpg",
        featured: true,
        new: false,
        limited: true
    },
    {
        id: 5,
        name: "Good Karma Crewneck",
        category: "crewnecks",
        type: "Crewneck",
        price: 145,
        colors: ["Sage", "Cream"],
        description: "Relaxed crewneck with 'GOOD KARMA ONLY' embroidered chest detail.",
        details: ["100% Cotton", "Relaxed fit", "Chain stitch embroidery", "Garment dyed"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        image: "images/hero-trust-karma.jpg",
        featured: false,
        new: true,
        limited: false
    },
    {
        id: 6,
        name: "KARMA Trucker Hat",
        category: "accessories",
        type: "Hat",
        price: 55,
        colors: ["Black/White", "Sand/Brown"],
        description: "Classic trucker silhouette with embroidered KARMA logo. Adjustable snapback.",
        details: ["Cotton front", "Mesh back", "Snapback closure", "Embroidered logo"],
        sizes: ["One Size"],
        image: "images/hero-trust-karma.jpg",
        featured: false,
        new: false,
        limited: false
    },
    {
        id: 7,
        name: "Coming For You Tee",
        category: "tees",
        type: "T-Shirt",
        price: 85,
        colors: ["Cream", "Black"],
        description: "Statement tee with 'KARMA IS COMING FOR YOU' back print. Boxy cropped fit.",
        details: ["100% Cotton", "Boxy fit", "Back print", "Cropped length"],
        sizes: ["S", "M", "L", "XL"],
        image: "images/hero-trust-karma.jpg",
        featured: false,
        new: true,
        limited: false
    },
    {
        id: 8,
        name: "Bad Karma Tee",
        category: "tees",
        type: "T-Shirt",
        price: 75,
        colors: ["Black", "Charcoal"],
        description: "Minimal tee with 'BAD KARMA' small chest print. Washed black finish.",
        details: ["100% Cotton", "Relaxed fit", "Chest print", "Pre-washed"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        image: "images/hero-trust-karma.jpg",
        featured: false,
        new: false,
        limited: false
    },
    {
        id: 9,
        name: "Fear No Karma Hoodie",
        category: "hoodies",
        type: "Hoodie",
        price: 185,
        colors: ["Black"],
        description: "All-black hoodie with tonal 'FEAR NO KARMA' puff print. Murdered out aesthetic.",
        details: ["100% Cotton", "Oversized fit", "Puff print", "Tonal details"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        image: "images/hero-trust-karma.jpg",
        featured: true,
        new: false,
        limited: false
    },
    {
        id: 10,
        name: "KARMA Beanie",
        category: "accessories",
        type: "Beanie",
        price: 45,
        colors: ["Black", "Sand", "Sage"],
        description: "Ribbed knit beanie with embroidered KARMA logo. Cuffed design.",
        details: ["100% Acrylic", "Ribbed knit", "Cuffed design", "Embroidered logo"],
        sizes: ["One Size"],
        image: "images/hero-trust-karma.jpg",
        featured: false,
        new: false,
        limited: false
    }
];

// Export for use in app.js
if (typeof module !== 'undefined' && module.exports) {
    module.exports = PRODUCTS;
}
